name: exercise_3
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=23.3.1
  - mlflow=1.14.1
  - hydra-core=1.0.6
  - protobuf=3.20
  - numpy=1.23.5
  - pip:
      - wandb==0.16.0